sonar.projectKey=ULL-ESIT-PAI-2025-2026_2025-2026-pai-sonarqube-2025-2026-pai-sonarqube
sonar.organization=ull-esit-pai-2025-2026

# Ubicación del código fuente
sonar.sources=src

# Exclusiones (para que no analice librerías de terceros)
sonar.exclusions=node_modules/**, dist/**

# Codificación
sonar.sourceEncoding=UTF-8

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=2025-2026-pai-sonarqube-2025-2026-pai-sonarqube
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8