sonar.projectKey=practica_5
sonar.host.url=http://localhost:9000
sonar.token=sqp_6e0d5e9a759c2f6e22890a2b0d6de5c45f7592c1
# Exclude dependencies and tests from the analysis
sonar.sources=src
sonar.tests=tests

# 2. Ignorar archivos .js solo en la fuente (src)
sonar.exclusions=**/*.js

# 3. Cobertura
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
