sonar.projectKey=practica_5
sonar.sources=. 
sonar.host.url=http://localhost:9000
sonar.token=sqp_6e0d5e9a759c2f6e22890a2b0d6de5c45f7592c1
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

# (Opcional) Si quieres que Sonar sepa cuáles son tus archivos de test
sonar.tests=./
sonar.test.inclusions=**/*.test.ts,**/*.test.js
