sonar.projectKey=practica_5
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_c676b54ac1688ccda35cf39451dca4bae37927a1
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**
# For test coverage
sonar.tests=tests
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
