sonar.projectKey=practica_9
sonar.sources=. 
sonar.host.url=http://localhost:9000
sonar.login=sqp_ae720cf870a01ed21858991fea15ee69c956000e
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**,**/*.test.ts
