sonar.projectKey=practica_9
sonar.sources=. 
sonar.host.url=http://localhost:9000
sonar.login=sqp_c1e5ca77d3c375c40001e0dcf8963c595853213f
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**,**/*.test.ts
