sonar.projectKey=practica_9
sonar.sources=. 
sonar.host.url=http://localhost:9000
sonar.login=sqp_b536a79b3b9351c2ad8e83e9366fb2066da15deb
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**,**/*.test.ts
