sonar.projectKey=practica_8
sonar.sources=. 
sonar.host.url=http://localhost:9000
sonar.login=sqp_808b4b422972e7f34d9826c19be9fbc1163c6db8
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**,**/*.test.ts
