sonar.projectKey=practica_8
sonar.sources=. 
sonar.host.url=http://localhost:9000
sonar.login=sqp_fdf34c76d62c2ee8f57f1c1c19f80771961663ac
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**,**/*.test.ts
