sonar.projectKey=examples
sonar.sources=. 
sonar.host.url=http://localhost:9000
sonar.login=sqp_d4fd195f2c7f748e63d5259e13b1b4beefa7d1d4
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**
sonar.eslint.reportPaths=eslint-report.json
