sonar.projectKey=examples
sonar.sources=. 
sonar.host.url=http://localhost:9000
sonar.login=sqp_ef814fb3bf727140f850cf9ba3f8a81ce1c8351a
# Exclude dependencies and tests from the analysis
sonar.exclusions=node_modules/**,**/*.test.ts
